/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DrugManager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Pharmacy.Drug;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class CreateDrugJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDrugJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;

    public CreateDrugJPanel(JPanel upc, Enterprise enterprise) {
        initComponents();
        userProcessContainer = upc;
        this.enterprise = enterprise;

        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) drugjTable1.getModel();

        dtm.setRowCount(0);

        PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise) enterprise;
        for (Drug drug : pce.getDrugList()) {
            {
                Object[] row = new Object[3];
                row[0] = drug;
                row[1] = drug.getDrugID();
                row[2] = drug.getFdaStatus();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        headingjLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idjTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        strengthjComboBox1 = new javax.swing.JComboBox();
        strengthjTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        specificationjTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        stabilityjTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dosagejTextField5 = new javax.swing.JTextField();
        pricejTextField7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugjTable1 = new javax.swing.JTable();
        deletejButton2 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        setMedicalGuidelinesjButton1 = new javax.swing.JButton();
        refreshjButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Drug Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 239, -1, -1));
        add(namejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 236, 166, -1));

        headingjLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headingjLabel2.setText("ADD DRUG HERE:");
        add(headingjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel3.setText("Drug ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 277, -1, -1));
        add(idjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 274, 166, -1));

        jLabel4.setText("Strength:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 315, -1, -1));

        strengthjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mG", "mL", "w/W", "v/V" }));
        add(strengthjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 312, -1, -1));

        strengthjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthjTextField3ActionPerformed(evt);
            }
        });
        strengthjTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                strengthjTextField3KeyReleased(evt);
            }
        });
        add(strengthjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 312, 83, -1));

        jLabel5.setText("Specification:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        specificationjTextArea1.setColumns(20);
        specificationjTextArea1.setRows(5);
        jScrollPane1.setViewportView(specificationjTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jLabel6.setText("Stability:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 363, -1, -1));
        add(stabilityjTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 360, 166, -1));

        jLabel7.setText("Dosage:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 401, -1, -1));
        add(dosagejTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 398, 166, -1));

        pricejTextField7.setToolTipText("price in dollars ($)");
        pricejTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pricejTextField7KeyReleased(evt);
            }
        });
        add(pricejTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 166, -1));

        drugjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Drug ID", "Drug Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugjTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 580, 100));

        deletejButton2.setText("Delete");
        deletejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton2ActionPerformed(evt);
            }
        });
        add(deletejButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel2.setText("Price:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        setMedicalGuidelinesjButton1.setText("Set Medical Guidelines >>");
        setMedicalGuidelinesjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMedicalGuidelinesjButton1ActionPerformed(evt);
            }
        });
        add(setMedicalGuidelinesjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 170, -1));

        refreshjButton1.setText("Refresh");
        refreshjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButton1ActionPerformed(evt);
            }
        });
        add(refreshjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel8.setText("$");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 20, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deletejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton2ActionPerformed
        // TODO add your handling code here:
        int row = drugjTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "select a row");
        } else {
            int selectedValue = JOptionPane.showConfirmDialog(null, "Are you Sure you want to Delete?", "WARNING", JOptionPane.YES_NO_OPTION);

            if (selectedValue == JOptionPane.YES_OPTION) {
                Drug drug = (Drug) drugjTable1.getValueAt(row, 0);
                PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise) enterprise;
                pce.getDrugList().remove(drug);

                populateTable();
            } else {
                return;
            }
        }
    }//GEN-LAST:event_deletejButton2ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void setMedicalGuidelinesjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMedicalGuidelinesjButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String drugName = namejTextField1.getText();
            String drugID = idjTextField2.getText();
            String strength = strengthjTextField3.getText() + " " + strengthjComboBox1.getSelectedItem();
            String specification = specificationjTextArea1.getText();
            String stability = stabilityjTextField4.getText();
            String dosage = dosagejTextField5.getText();
            float price = Float.parseFloat(pricejTextField7.getText());

        

        if (drugName.isEmpty() || drugID.isEmpty() || strength.isEmpty() || specification.isEmpty()
                || stability.isEmpty() || dosage.isEmpty() || String.valueOf(price).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field(s) cannot be empty.");
            return;
        }

        Drug drug = new Drug();
        drug.setDrugName(drugName);
        drug.setDrugID(drugID);
        drug.setStrength(strength);
        drug.setManufacturingCompany(enterprise);
        drug.setSpecification(specification);
        drug.setStability(stability);
        drug.setDosage(dosage);
        drug.setPrice(price);
        drug.setFdaStatus("not sent for approval");

        
        SetMedicalGuideJPanel smgjp = new SetMedicalGuideJPanel(userProcessContainer, drug, enterprise);
        userProcessContainer.add("setMedicalGuidelinesJP", smgjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Enter valid values");
            return;
        }

    }//GEN-LAST:event_setMedicalGuidelinesjButton1ActionPerformed

    private void strengthjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strengthjTextField3ActionPerformed

    private void strengthjTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strengthjTextField3KeyReleased
        // TODO add your handling code here:
            if ((Pattern.matches("^[a-zA-Z]+$", strengthjTextField3.getText()))) {
                strengthjTextField3.setText(null);
            }
    }//GEN-LAST:event_strengthjTextField3KeyReleased

    private void pricejTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricejTextField7KeyReleased
        // TODO add your handling code here:
            if ((Pattern.matches("^[a-zA-Z]+$", pricejTextField7.getText()))) {
                pricejTextField7.setText(null);
            }
    }//GEN-LAST:event_pricejTextField7KeyReleased

    private void refreshjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton deletejButton2;
    private javax.swing.JTextField dosagejTextField5;
    private javax.swing.JTable drugjTable1;
    private javax.swing.JLabel headingjLabel2;
    private javax.swing.JTextField idjTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JTextField pricejTextField7;
    private javax.swing.JButton refreshjButton1;
    private javax.swing.JButton setMedicalGuidelinesjButton1;
    private javax.swing.JTextArea specificationjTextArea1;
    private javax.swing.JTextField stabilityjTextField4;
    private javax.swing.JComboBox strengthjComboBox1;
    private javax.swing.JTextField strengthjTextField3;
    // End of variables declaration//GEN-END:variables
}
