/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DrugManager;

import Business.Enterprise.Enterprise;
import Business.Organization.DrugManagementOrganization;
import Business.Organization.Organization;
import UI.AdministrativeRole.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aayush
 */
public class DrugManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
//    private Organization drugMngOrg;
    private Organization drugRegOrg;

    public DrugManagerWorkAreaJPanel(JPanel upc, Enterprise enterprise,Organization org) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = enterprise;
        drugRegOrg=org;

//        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
//            if (o instanceof DrugManagementOrganization) {
//                drugMngOrg = o;
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createDrugjButton1 = new javax.swing.JButton();
        fdaApprovaljButton1 = new javax.swing.JButton();

        createDrugjButton1.setText("Create Drug");
        createDrugjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDrugjButton1ActionPerformed(evt);
            }
        });

        fdaApprovaljButton1.setText("Check FDA Approval");
        fdaApprovaljButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdaApprovaljButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fdaApprovaljButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(createDrugjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(createDrugjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(fdaApprovaljButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createDrugjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDrugjButton1ActionPerformed
        // TODO add your handling code here:
        CreateDrugJPanel cdjp = new CreateDrugJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("CreateDrugJPanel", cdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_createDrugjButton1ActionPerformed

    private void fdaApprovaljButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdaApprovaljButton1ActionPerformed
        // TODO add your handling code here:
        SendForFdaApprovalJPanel sffajp = new SendForFdaApprovalJPanel(userProcessContainer,enterprise,drugRegOrg);
        userProcessContainer.add("SendForFdaApproval", sffajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_fdaApprovaljButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDrugjButton1;
    private javax.swing.JButton fdaApprovaljButton1;
    // End of variables declaration//GEN-END:variables
}
