/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DrugManager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Organization.Organization;
import Business.Pharmacy.Drug;
import Business.WorkQueue.DrugMngrToFDAWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class SendForFdaApprovalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendForFdaApprovalJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization drugRegOrg;

    public SendForFdaApprovalJPanel(JPanel upc, Enterprise enterprise, Organization o) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = enterprise;
        drugRegOrg = o;

        populateTable();

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) drugjTable1.getModel();

        dtm.setRowCount(0);

        PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise) enterprise;
        for (Drug drug : pce.getDrugList()) {
            {
                Object[] row = new Object[3];
                row[0] = drug;
                row[1] = drug.getDrugID();
                row[2] = drug.getFdaStatus();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        drugjTable1 = new javax.swing.JTable();
        backjButton1 = new javax.swing.JButton();
        sendRequestjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messagejTextField1 = new javax.swing.JTextField();

        drugjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Drug ID", "FDA Aprroval Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugjTable1);

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        sendRequestjButton1.setText("Send Approval Request");
        sendRequestjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestjButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Message:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(messagejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(sendRequestjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(messagejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(sendRequestjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(backjButton1)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void sendRequestjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestjButton1ActionPerformed
        // TODO add your handling code here:

        String message = messagejTextField1.getText();

        int row = drugjTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "select a row");
        } else if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "message field cannot be empty.");
        } else {

            Drug drug = (Drug) drugjTable1.getValueAt(row, 0);

            if(drug.getFdaStatus().equalsIgnoreCase("pending"))
            {
                JOptionPane.showMessageDialog(null, "Request already sent.");
                return;
            }
            
            drug.setFdaStatus("pending");
            DrugMngrToFDAWorkRequest request = new DrugMngrToFDAWorkRequest();
            request.setDrug(drug);
            request.setEntId(String.valueOf(enterprise.getOrganizationID()));
            request.setMessage(message);
            request.setEnterpriseName(enterprise.getName());

            drugRegOrg.getWorkQueue().getWorkRequestList().add(request);
            enterprise.getWorkQueue().getWorkRequestList().add(request);

            populateTable();

        }
    }//GEN-LAST:event_sendRequestjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable drugjTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messagejTextField1;
    private javax.swing.JButton sendRequestjButton1;
    // End of variables declaration//GEN-END:variables
}
