/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.Creator;

import Business.Organization.ICDOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aayush
 */
public class ICDWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ICDWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private ICDOrganization iCDOrg;
    public ICDWorkAreaJPanel(JPanel userProcessContainer, ICDOrganization iCDOrg) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.iCDOrg=iCDOrg;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerDiseasejButton1 = new javax.swing.JButton();

        registerDiseasejButton1.setText("Register Disease and Health issues");
        registerDiseasejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerDiseasejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(registerDiseasejButton1)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(registerDiseasejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerDiseasejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerDiseasejButton1ActionPerformed
        // TODO add your handling code here:
        
        RegisterDiseaseAndHealthIssues rdahi = new RegisterDiseaseAndHealthIssues(userProcessContainer, iCDOrg);
        userProcessContainer.add("RegisterDiseaseAndHealthIssuesJP", rdahi);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerDiseasejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton registerDiseasejButton1;
    // End of variables declaration//GEN-END:variables
}
