/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Creator;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Organization.Organization;
import Business.Pharmacy.Drug;
import Business.WorkQueue.DrugMngrToFDAWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class ManageDrugAprrovalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugAprrovalJPanel
     */
    private JPanel userProcessContainer;
    private Organization drugRegOrg;

    public ManageDrugAprrovalJPanel(JPanel upc, Organization o) {
        initComponents();
        userProcessContainer = upc;
        drugRegOrg = o;

//        for(WorkRequest wr : drugRegOrg.getWorkQueue().getWorkRequestList())
//        {
//            
//        }
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) drugjTable1.getModel();

        dtm.setRowCount(0);

        for (WorkRequest request : drugRegOrg.getWorkQueue().getWorkRequestList()) {
            DrugMngrToFDAWorkRequest dmr = (DrugMngrToFDAWorkRequest) request;
            Object[] row = new Object[6];
            row[0] = dmr.getEntId();
            row[1] = dmr.getEnterpriseName();
            row[2] = dmr.getDrug().getDrugID();
            row[3] = dmr.getDrug();
            row[4] = dmr;
            row[5] = dmr.getDrug().getFdaStatus();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        drugjTable1 = new javax.swing.JTable();
        approvedissapprovejComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        submitjButton1 = new javax.swing.JButton();
        viewDrugjButton1 = new javax.swing.JButton();
        processjButton1 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        drugjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Enterprise ID", "Enterprise Name", "Drug ID", "Drug Name", "Message", "FDA Aprroval Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugjTable1);

        approvedissapprovejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Approve", "Reject" }));

        jLabel1.setText("Status:");

        submitjButton1.setText("Submit");
        submitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton1ActionPerformed(evt);
            }
        });

        viewDrugjButton1.setText("View Drug Details");
        viewDrugjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDrugjButton1ActionPerformed(evt);
            }
        });

        processjButton1.setText("Process");
        processjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processjButton1ActionPerformed(evt);
            }
        });

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(48, 48, 48)
                            .addComponent(approvedissapprovejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(246, 246, 246))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(submitjButton1)
                            .addGap(306, 306, 306)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewDrugjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(processjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(backjButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDrugjButton1)
                    .addComponent(processjButton1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approvedissapprovejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addComponent(submitjButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton1ActionPerformed
        // TODO add your handling code here:

        int selectedRow = drugjTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a Row.");
            return;
        }
        DrugMngrToFDAWorkRequest dmr = (DrugMngrToFDAWorkRequest) drugjTable1.getValueAt(selectedRow, 4);

        if (approvedissapprovejComboBox1.getSelectedItem().equals("Approve")) {
            dmr.getDrug().setFdaStatus("Approved");

        } else if (approvedissapprovejComboBox1.getSelectedItem().equals("Reject")) {
            dmr.getDrug().setFdaStatus("Rejected");
        }

        populateTable();

    }//GEN-LAST:event_submitjButton1ActionPerformed

    private void viewDrugjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDrugjButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugjTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a Row.");
            return;
        }
        DrugMngrToFDAWorkRequest dmr = (DrugMngrToFDAWorkRequest) drugjTable1.getValueAt(selectedRow, 4);
        Drug drug = (Drug) dmr.getDrug();
        ViewDrugJPanel vdjp = new ViewDrugJPanel(userProcessContainer, drug);
        userProcessContainer.add("ViewDrugJPanel", vdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDrugjButton1ActionPerformed

    private void processjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processjButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugjTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a Row.");
            return;
        }
        DrugMngrToFDAWorkRequest dmr = (DrugMngrToFDAWorkRequest) drugjTable1.getValueAt(selectedRow, 4);
        
        dmr.getDrug().setFdaStatus("Processing");
        
        populateTable();
    }//GEN-LAST:event_processjButton1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox approvedissapprovejComboBox1;
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable drugjTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processjButton1;
    private javax.swing.JButton submitjButton1;
    private javax.swing.JButton viewDrugjButton1;
    // End of variables declaration//GEN-END:variables
}
