/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PatientRole;

import Business.EcoSystem;
import Business.Forum.Disease;
import Business.Organization.ICDOrganization;
import Business.Organization.Organization;
import Business.Person.Patient;
import Business.WorkQueue.WorkQueue;
import UI.AdministrativeRole.Pharmacy.ViewBroadcastJPanel;
import UI.Forum.DiseaseForumJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Aayush
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Patient patient;

    public PatientWorkAreaJPanel(JPanel upc, EcoSystem system, Patient patient) {
        initComponents();
        userProcessContainer = upc;
        this.system = system;
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageWorkRequestjButton1 = new javax.swing.JButton();
        viewBroadcastsjButton2 = new javax.swing.JButton();
        getSocializejButton1 = new javax.swing.JButton();

        manageWorkRequestjButton1.setText("Manage Work Request");
        manageWorkRequestjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWorkRequestjButton1ActionPerformed(evt);
            }
        });

        viewBroadcastsjButton2.setText("View Broadcast(s)");
        viewBroadcastsjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBroadcastsjButton2ActionPerformed(evt);
            }
        });

        getSocializejButton1.setText("Get Socialize");
        getSocializejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSocializejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewBroadcastsjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageWorkRequestjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(getSocializejButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(manageWorkRequestjButton1)
                .addGap(47, 47, 47)
                .addComponent(viewBroadcastsjButton2)
                .addGap(47, 47, 47)
                .addComponent(getSocializejButton1)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageWorkRequestjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWorkRequestjButton1ActionPerformed
        // TODO add your handling code here:
        ManagePatientWorkRequestJPanel mpwrjp = new ManagePatientWorkRequestJPanel(userProcessContainer, system, patient);
        userProcessContainer.add("managePatientWRJPanel", mpwrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageWorkRequestjButton1ActionPerformed

    private void viewBroadcastsjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBroadcastsjButton2ActionPerformed
        // TODO add your handling code here:

        WorkQueue wq = patient.getWorkQueue();
        ViewBroadcastJPanel vbjp = new ViewBroadcastJPanel(userProcessContainer, wq);
        userProcessContainer.add("viewbroadcastPatientJPanel", vbjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewBroadcastsjButton2ActionPerformed

    private void getSocializejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSocializejButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Disease> list = new ArrayList();
        ICDOrganization iCDOrg=null;
        for (Organization org : system.getCreator().getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof ICDOrganization) {
                iCDOrg = (ICDOrganization) org;
                for (Disease d : iCDOrg.getWorldDiseaseList()) {
                    list.add(d);
                }
            }
            DiseaseForumJPanel dfjp = new DiseaseForumJPanel(userProcessContainer, list, iCDOrg, patient);
            userProcessContainer.add("DiseaseForumJPanel", dfjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_getSocializejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getSocializejButton1;
    private javax.swing.JButton manageWorkRequestjButton1;
    private javax.swing.JButton viewBroadcastsjButton2;
    // End of variables declaration//GEN-END:variables
}
