/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdministrativeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Person.Doctor;
import Business.Person.Patient;
import Business.Person.Person;
import Business.Role.PatientRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Aayush
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization orgPatient;
    private Organization orgDoctor;
    private Organization cPO;

    public CreatePatientJPanel(JPanel userProcesContainer, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcesContainer;
        this.enterprise = enterprise;
        this.cPO=organization;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof PatientOrganization) {
                this.orgPatient = org;
            }
            if (org instanceof DoctorOrganization) {
                this.orgDoctor = org;
            }
        }
        populateDoctorCombo();
        
        jDateChooser1.getDateEditor().setEnabled(false);

    }
    
    private void populateDoctorCombo() {
        
        prefferedDoctorjComboBox2.removeAllItems();
        for(Person person: orgDoctor.getPersonDirectory().getPersonList())
        {
            if(person instanceof Doctor)
            {
                Doctor doctor = (Doctor)person;
                prefferedDoctorjComboBox2.addItem(doctor);
            }
        }
    }
    
    private void blankifyPanel()
    {
        usernamejTextField1.setText("");
        passwordjTextField2.setText("");
        
        firstNamejTextField3.setText("");
        lastNamejTextField1.setText("");
        uniqueIDjTextField1.setText("");
        line1AddressjTextField2.setText("");
        cityjTextField3.setText("");
        countryjTextField5.setText("");
        jDateChooser1.setDateFormatString("");
        statejTextField4.setText("");
        primaryLanguagejTextField1.setText("");
        primaryContactjTextField1.setText("");
        allergiesjTextField1.setText("");
        descriptionjTextField1.setText("");
        insuranceIDjTextField2.setText("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNamejLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submitjButton1 = new javax.swing.JButton();
        lastNamejLabel1 = new javax.swing.JLabel();
        lastNamejTextField1 = new javax.swing.JTextField();
        firstNamejTextField3 = new javax.swing.JTextField();
        passwordjTextField2 = new javax.swing.JTextField();
        usernamejTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        genderjComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        uniqueIDjTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        primaryContactjTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        line1AddressjTextField2 = new javax.swing.JTextField();
        cityjTextField3 = new javax.swing.JTextField();
        statejTextField4 = new javax.swing.JTextField();
        countryjTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        descriptionjTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        primaryLanguagejTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        maritalStatusjComboBox1 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        allergiesjTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        prefferedDoctorjComboBox2 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        insuranceIDjTextField2 = new javax.swing.JTextField();
        backjButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNamejLabel5.setText("First Name:");
        add(firstNamejLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        submitjButton1.setText("Submit");
        submitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton1ActionPerformed(evt);
            }
        });
        add(submitjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 140, 40));

        lastNamejLabel1.setText("Last Name:");
        add(lastNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        add(lastNamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 122, -1));
        add(firstNamejTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 122, -1));
        add(passwordjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 122, -1));
        add(usernamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 122, -1));

        jLabel3.setText("UserName:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setText("Gender:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        genderjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        add(genderjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 122, -1));

        jLabel5.setText("Unique ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        add(uniqueIDjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 122, -1));

        jLabel6.setText("DOB:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 122, -1));

        jLabel7.setText("Primary Contact Number:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));
        add(primaryContactjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ADDRESS");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        jLabel9.setText("City:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        jLabel10.setText("State:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        jLabel11.setText("Country:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, -1, -1));

        jLabel12.setText("Line 1:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        line1AddressjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line1AddressjTextField2ActionPerformed(evt);
            }
        });
        add(line1AddressjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 390, -1));
        add(cityjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 91, -1));
        add(statejTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 102, -1));
        add(countryjTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 101, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("User Account Details:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Personal Details:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel15.setText("Description:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));
        add(descriptionjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 150, -1));

        jLabel16.setText("Primary Language:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, 20));
        add(primaryLanguagejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 150, -1));

        jLabel17.setText("Marital Status:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        maritalStatusjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", "Divorced", "Widowed" }));
        add(maritalStatusjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 150, -1));

        jLabel18.setText("Allergies:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));
        add(allergiesjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 150, -1));

        jLabel19.setText("Preffered Doctor:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        prefferedDoctorjComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(prefferedDoctorjComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 150, -1));

        jLabel20.setText("Insurance ID:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        add(insuranceIDjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 120, -1));

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton1ActionPerformed
        // TODO add your handling code here:
        String userName = usernamejTextField1.getText();
        String password = passwordjTextField2.getText();
        String fname = firstNamejTextField3.getText();
        String lname = lastNamejTextField1.getText();
        String gender = String.valueOf(genderjComboBox1.getSelectedItem());
        String uniqueID = uniqueIDjTextField1.getText();
        String InsuranceID = insuranceIDjTextField2.getText();
        
        String DateFormat = "EEE, MMM d, yyyy";
        SimpleDateFormat sdf = new SimpleDateFormat(DateFormat);
        Date d = jDateChooser1.getDate();
        Date Dob = d;
        
        if (((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Date Field cannot be empty");
            return;
        }
        
        Doctor doctor = (Doctor) prefferedDoctorjComboBox2.getSelectedItem();

        String maritalStatus = (String) maritalStatusjComboBox1.getSelectedItem();
        String allergies = allergiesjTextField1.getText();
        String primaryContact = primaryContactjTextField1.getText();
        String description = descriptionjTextField1.getText();
        String line1 = line1AddressjTextField2.getText();
        String city = cityjTextField3.getText();
        String state = statejTextField4.getText();
        String country = countryjTextField5.getText();
        String primaryLanguage = primaryLanguagejTextField1.getText();

        if (!(userName.isEmpty() || password.isEmpty() || fname.isEmpty() || lname.isEmpty() || InsuranceID.isEmpty() || doctor.getFirstName().isEmpty()
                || uniqueID.isEmpty() || String.valueOf(Dob).isEmpty() || description.isEmpty() || primaryContact.isEmpty() || line1.isEmpty()
                || city.isEmpty() || state.isEmpty() || country.isEmpty() || primaryLanguage.isEmpty() || allergies.isEmpty()
                || usernamejTextField1.getText().isEmpty() || passwordjTextField2.getText().isEmpty())) {

            if(EcoSystem.checkIfUsernameUnique(userName) == false)
            {
                return;
            }
                Patient patient = new Patient();
               

                UserAccount userAccount = cPO.getUserAccountDirectory().createUserAccount(userName, password, patient, new PatientRole());
                
                patient.setFirstName(fname);
                patient.setLastName(lname);
                patient.setGender(gender);
                patient.setUniqueId(uniqueID);
                patient.setAddressline1(line1);
                patient.setCity(city);
                patient.setCountry(country);
                patient.setDateOfBirth(Dob);
                patient.setState(state);
                patient.setPrimaryLanguage(primaryLanguage);
                patient.setPrimaryContact(primaryContact);
                patient.setAllergies(allergies);
                patient.setDescription(description);
                patient.setInsuranceID(InsuranceID);
                patient.setJoiningDate(new Date());
                patient.setPrefferedDoctor(doctor);
                patient.setMaritalStatus(maritalStatus);
                
                cPO.getPersonDirectory().createPerson(patient);
                orgPatient.getPersonDirectory().createPerson(patient);
                
                blankifyPanel();

        }
        else {
            JOptionPane.showMessageDialog(null, "Field(s) cannot be left blank");
        }
    }//GEN-LAST:event_submitjButton1ActionPerformed

    private void line1AddressjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line1AddressjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_line1AddressjTextField2ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField allergiesjTextField1;
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField cityjTextField3;
    private javax.swing.JTextField countryjTextField5;
    private javax.swing.JTextField descriptionjTextField1;
    private javax.swing.JLabel firstNamejLabel5;
    private javax.swing.JTextField firstNamejTextField3;
    private javax.swing.JComboBox genderjComboBox1;
    private javax.swing.JTextField insuranceIDjTextField2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lastNamejLabel1;
    private javax.swing.JTextField lastNamejTextField1;
    private javax.swing.JTextField line1AddressjTextField2;
    private javax.swing.JComboBox maritalStatusjComboBox1;
    private javax.swing.JTextField passwordjTextField2;
    private javax.swing.JComboBox prefferedDoctorjComboBox2;
    private javax.swing.JTextField primaryContactjTextField1;
    private javax.swing.JTextField primaryLanguagejTextField1;
    private javax.swing.JTextField statejTextField4;
    private javax.swing.JButton submitjButton1;
    private javax.swing.JTextField uniqueIDjTextField1;
    private javax.swing.JTextField usernamejTextField1;
    // End of variables declaration//GEN-END:variables
}
