/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdministrativeRole;

import Business.Person.Patient;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Aayush
 */
public class ViewPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;

    public ViewPatientJPanel(JPanel upc, Patient patient) {
        initComponents();
        userProcessContainer = upc;
        this.patient = patient;
        populatePanel();
        
        jDateUpdateChooser1.setVisible(false);
        dobUpdatejLabel13.setVisible(false);
        mariStatUpdatejLabel22.setVisible(false);
        maritalStatusUpdatejComboBox1.setVisible(false);
    }

    private void populatePanel() {

        firstNamejTextField3.setText(patient.getFirstName());
        lastNamejTextField1.setText(patient.getLastName());
        genderjTextField1.setText(patient.getGender());
        uniqueIDjTextField1.setText(patient.getUniqueId());
        line1AddressjTextField2.setText(patient.getAddressline1());
        cityjTextField3.setText(patient.getCity());
        countryjTextField5.setText(patient.getCountry());
        dobjTextField1.setText(String.valueOf(patient.getDateOfBirth()));
        statejTextField4.setText(patient.getState());
        primaryLanguagejTextField1.setText(patient.getPrimaryLanguage());
        primaryContactjTextField1.setText(patient.getPrimaryContact());
        allergiesjTextField1.setText(patient.getAllergies());
        descriptionjTextField1.setText(patient.getDescription());
        insuranceIDjTextField2.setText(patient.getInsuranceID());
        dateOfRegistrationjTextField1.setText(String.valueOf(patient.getJoiningDate()));
        prefferedDoctorjTextField1.setText(String.valueOf(patient.getPrefferedDoctor()));
        maritalStatusjTextField1.setText(patient.getMaritalStatus());
        mrnjTextField1.setText(String.valueOf(patient.getMRN()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNamejLabel5 = new javax.swing.JLabel();
        lastNamejLabel1 = new javax.swing.JLabel();
        lastNamejTextField1 = new javax.swing.JTextField();
        firstNamejTextField3 = new javax.swing.JTextField();
        genderOldjLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uniqueIDjTextField1 = new javax.swing.JTextField();
        dobOldjLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        primaryContactjTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        line1AddressjTextField2 = new javax.swing.JTextField();
        cityjTextField3 = new javax.swing.JTextField();
        statejTextField4 = new javax.swing.JTextField();
        countryjTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        descriptionjTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        primaryLanguagejTextField1 = new javax.swing.JTextField();
        mariStatOldjLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        allergiesjTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        insuranceIDjTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mrnjTextField1 = new javax.swing.JTextField();
        dORegjLabel21 = new javax.swing.JLabel();
        dateOfRegistrationjTextField1 = new javax.swing.JTextField();
        genderjTextField1 = new javax.swing.JTextField();
        maritalStatusjTextField1 = new javax.swing.JTextField();
        prefferedDoctorjTextField1 = new javax.swing.JTextField();
        dobjTextField1 = new javax.swing.JTextField();
        backjButton1 = new javax.swing.JButton();
        updatejButton1 = new javax.swing.JButton();
        submitjButton2 = new javax.swing.JButton();
        jDateUpdateChooser1 = new com.toedter.calendar.JDateChooser();
        dobUpdatejLabel13 = new javax.swing.JLabel();
        maritalStatusUpdatejComboBox1 = new javax.swing.JComboBox();
        mariStatUpdatejLabel22 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNamejLabel5.setText("First Name:");
        add(firstNamejLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 134, -1, -1));

        lastNamejLabel1.setText("Last Name:");
        add(lastNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 164, -1, -1));
        add(lastNamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 164, 122, -1));
        add(firstNamejTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 134, 122, -1));

        genderOldjLabel2.setText("Gender:");
        add(genderOldjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 204, -1, -1));

        jLabel5.setText("Unique ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 241, -1, -1));
        add(uniqueIDjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 241, 122, -1));

        dobOldjLabel6.setText("DOB:");
        add(dobOldjLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 281, -1, -1));

        jLabel7.setText("Primary Contact Number:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 174, -1, -1));
        add(primaryContactjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 174, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ADDRESS");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 392, -1, -1));

        jLabel9.setText("City:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 442, -1, -1));

        jLabel10.setText("State:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 442, -1, -1));

        jLabel11.setText("Country:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 442, -1, -1));

        jLabel12.setText("Line 1:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 412, -1, -1));

        line1AddressjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line1AddressjTextField2ActionPerformed(evt);
            }
        });
        add(line1AddressjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 412, 390, -1));
        add(cityjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 462, 91, -1));
        add(statejTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 462, 102, -1));
        add(countryjTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 462, 101, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Personal Details:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 52, -1, -1));

        jLabel15.setText("Description:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 137, -1, -1));
        add(descriptionjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 134, 150, -1));

        jLabel16.setText("Primary Language:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 211, -1, 20));
        add(primaryLanguagejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 211, 150, -1));

        mariStatOldjLabel17.setText("Marital Status:");
        add(mariStatOldjLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 251, -1, -1));

        jLabel18.setText("Allergies:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 288, -1, -1));
        add(allergiesjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 288, 150, -1));

        jLabel19.setText("Preffered Doctor:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 328, -1, -1));

        jLabel20.setText("Insurance ID:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 318, -1, -1));
        add(insuranceIDjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 318, 120, -1));

        jLabel1.setText("MRN:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 99, -1, -1));

        mrnjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrnjTextField1ActionPerformed(evt);
            }
        });
        add(mrnjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 96, 122, -1));

        dORegjLabel21.setText("Date of Registration:");
        add(dORegjLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 99, -1, -1));
        add(dateOfRegistrationjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 96, 150, -1));
        add(genderjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 201, 122, -1));
        add(maritalStatusjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 248, 150, -1));
        add(prefferedDoctorjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 328, 150, -1));
        add(dobjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 278, 120, -1));

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 521, -1, -1));

        updatejButton1.setText("Update");
        updatejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton1ActionPerformed(evt);
            }
        });
        add(updatejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 46, -1, -1));

        submitjButton2.setText("Submit");
        submitjButton2.setEnabled(false);
        submitjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton2ActionPerformed(evt);
            }
        });
        add(submitjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 513, 139, -1));
        add(jDateUpdateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 122, -1));

        dobUpdatejLabel13.setText("DateOfBirth:");
        add(dobUpdatejLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 361, -1, -1));

        maritalStatusUpdatejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", "Divorced", "Widowed" }));
        add(maritalStatusUpdatejComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 150, -1));

        mariStatUpdatejLabel22.setText("Marital Status:");
        add(mariStatUpdatejLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void line1AddressjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line1AddressjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_line1AddressjTextField2ActionPerformed

    private void mrnjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrnjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrnjTextField1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void updatejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton1ActionPerformed
        // TODO add your handling code here:
        submitjButton2.setEnabled(true);
        updatejButton1.setEnabled(false);
        jDateUpdateChooser1.setVisible(true);
        dobUpdatejLabel13.setVisible(true);
        mariStatUpdatejLabel22.setVisible(true);
        maritalStatusUpdatejComboBox1.setVisible(true);
        dORegjLabel21.setVisible(false);
        dateOfRegistrationjTextField1.setVisible(false);
    }//GEN-LAST:event_updatejButton1ActionPerformed

    private void submitjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton2ActionPerformed
        // TODO add your handling code here:
        
        maritalStatusjTextField1.setVisible(true);
        mariStatOldjLabel17.setVisible(true);
        mariStatUpdatejLabel22.setVisible(false);
        maritalStatusjTextField1.setVisible(false);
        
        dobOldjLabel6.setVisible(false);
        dobjTextField1.setVisible(false);
        
        submitjButton2.setEnabled(false);
        updatejButton1.setEnabled(true);
        genderOldjLabel2.setVisible(false);
        genderjTextField1.setVisible(false);
        dORegjLabel21.setVisible(true);
        dateOfRegistrationjTextField1.setVisible(true);
        
        
        String fname = firstNamejTextField3.getText();
        String lname = lastNamejTextField1.getText();
        String uniqueID = uniqueIDjTextField1.getText();
        String InsuranceID = insuranceIDjTextField2.getText();
        
        String DateFormat = "EEE, MMM d, yyyy";
        SimpleDateFormat sdf = new SimpleDateFormat(DateFormat);
        Date d = jDateUpdateChooser1.getDate();
        Date Dob = d;
        
        if (((JTextField) jDateUpdateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Date Field cannot be empty");
            return;
        }
        

        String maritalStatus = (String) maritalStatusUpdatejComboBox1.getSelectedItem();
        String allergies = allergiesjTextField1.getText();
        String primaryContact = primaryContactjTextField1.getText();
        String description = descriptionjTextField1.getText();
        String line1 = line1AddressjTextField2.getText();
        String city = cityjTextField3.getText();
        String state = statejTextField4.getText();
        String country = countryjTextField5.getText();
        String primaryLanguage = primaryLanguagejTextField1.getText();

        if (!(fname.isEmpty() || lname.isEmpty() || InsuranceID.isEmpty() || uniqueID.isEmpty() 
                || String.valueOf(Dob).isEmpty() || description.isEmpty() 
                || primaryContact.isEmpty() || line1.isEmpty()|| city.isEmpty() || 
                state.isEmpty() || country.isEmpty() || primaryLanguage.isEmpty() || allergies.isEmpty())) {

                
                patient.setFirstName(fname);
                patient.setLastName(lname);
                patient.setUniqueId(uniqueID);
                patient.setAddressline1(line1);
                patient.setCity(city);
                patient.setCountry(country);
                patient.setDateOfBirth(Dob);
                patient.setState(state);
                patient.setPrimaryLanguage(primaryLanguage);
                patient.setPrimaryContact(primaryContact);
                patient.setAllergies(allergies);
                patient.setDescription(description);
                patient.setInsuranceID(InsuranceID);
                patient.setMaritalStatus(maritalStatus);
                
                JOptionPane.showMessageDialog(null, "Demographics updated.");
                populatePanel();
        }
        else {
            JOptionPane.showMessageDialog(null, "Field(s) cannot be left blank");
        }

        
        
    }//GEN-LAST:event_submitjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField allergiesjTextField1;
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField cityjTextField3;
    private javax.swing.JTextField countryjTextField5;
    private javax.swing.JLabel dORegjLabel21;
    private javax.swing.JTextField dateOfRegistrationjTextField1;
    private javax.swing.JTextField descriptionjTextField1;
    private javax.swing.JLabel dobOldjLabel6;
    private javax.swing.JLabel dobUpdatejLabel13;
    private javax.swing.JTextField dobjTextField1;
    private javax.swing.JLabel firstNamejLabel5;
    private javax.swing.JTextField firstNamejTextField3;
    private javax.swing.JLabel genderOldjLabel2;
    private javax.swing.JTextField genderjTextField1;
    private javax.swing.JTextField insuranceIDjTextField2;
    private com.toedter.calendar.JDateChooser jDateUpdateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lastNamejLabel1;
    private javax.swing.JTextField lastNamejTextField1;
    private javax.swing.JTextField line1AddressjTextField2;
    private javax.swing.JLabel mariStatOldjLabel17;
    private javax.swing.JLabel mariStatUpdatejLabel22;
    private javax.swing.JComboBox maritalStatusUpdatejComboBox1;
    private javax.swing.JTextField maritalStatusjTextField1;
    private javax.swing.JTextField mrnjTextField1;
    private javax.swing.JTextField prefferedDoctorjTextField1;
    private javax.swing.JTextField primaryContactjTextField1;
    private javax.swing.JTextField primaryLanguagejTextField1;
    private javax.swing.JTextField statejTextField4;
    private javax.swing.JButton submitjButton2;
    private javax.swing.JTextField uniqueIDjTextField1;
    private javax.swing.JButton updatejButton1;
    // End of variables declaration//GEN-END:variables
}
