/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.Forum;

import Business.Forum.Disease;
import Business.Forum.ForumTopic;
import Business.Organization.ICDOrganization;
import Business.Person.Patient;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class DiseaseForumJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiseaseForumJPanel
     */
    private JPanel userProcessContainer;
    private ArrayList<Disease>diseaseList;
    private ForumTopic forumTopic;
    private ICDOrganization iCDOrg;
    private Patient patient;
    
    public DiseaseForumJPanel(JPanel userProcessContainer, ArrayList<Disease>list, ICDOrganization iCDOrg,Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        diseaseList=list;
        this.iCDOrg = iCDOrg;
        this.patient=patient;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) diseasejTable1.getModel();

        dtm.setRowCount(0);

        for (Disease d : diseaseList) {
            Object[] row = new Object[2];
            row[0] = d;
            row[1] = d.getiCDCode();

            dtm.addRow(row);
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        diseasejTable1 = new javax.swing.JTable();
        goToForumjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        diseasejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Disease Name", "ICD Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(diseasejTable1);

        goToForumjButton1.setText("Go to Forum Topics>>");
        goToForumjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToForumjButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select a disease:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(goToForumjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(goToForumjButton1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goToForumjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToForumjButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = diseasejTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "select a row");
            return;
        }
        Disease d = (Disease) diseasejTable1.getValueAt(selectedRow, 0);
        
        ManageForumJPanel mfjp = new ManageForumJPanel(userProcessContainer, d, iCDOrg, patient);
        userProcessContainer.add("ManageForumJPanel", mfjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_goToForumjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable diseasejTable1;
    private javax.swing.JButton goToForumjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
