/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DoctorRole;

import Business.Encounter.Encounter;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Person.Doctor;
import Business.Person.Patient;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aayush
 */
public class AddemergencyEncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddemergencyEncounterJPanel
     */
    private JPanel userProcessContainer;
    private Doctor doctor;
    private Enterprise enterprise;
    private Patient patient;

    public AddemergencyEncounterJPanel(JPanel upc, Doctor doctor, Enterprise enterprise, Patient patient) {
        initComponents();
        this.doctor = doctor;
        this.enterprise = enterprise;
        userProcessContainer = upc;
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bloodPressurejTextField2 = new javax.swing.JTextField();
        heartRatejTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        respiratoryRatejTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        temperatureJTF = new javax.swing.JTextField();
        weightjTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        presciptionjTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        addEncounterjButton1 = new javax.swing.JButton();

        jLabel2.setText("Respiratory Rate:");

        jLabel3.setText("Heart Rate:");

        jLabel4.setText("Blood Pressure:");

        jLabel5.setText("Temperature:");

        jLabel6.setText("Weight:");

        presciptionjTextArea1.setColumns(20);
        presciptionjTextArea1.setRows(5);
        jScrollPane2.setViewportView(presciptionjTextArea1);

        jLabel7.setText("Prescription:");

        addEncounterjButton1.setText("Add Encounter");
        addEncounterjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEncounterjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(addEncounterjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(respiratoryRatejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(temperatureJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(weightjTextField3))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bloodPressurejTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(heartRatejTextField1))))
                    .addContainerGap(339, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(addEncounterjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(respiratoryRatejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(temperatureJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(weightjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(heartRatejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(bloodPressurejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(121, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEncounterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEncounterjButton1ActionPerformed
        // TODO add your handling code here:

        int RespRate = Integer.parseInt(respiratoryRatejTextField1.getText());
        int heartrate = Integer.parseInt(heartRatejTextField1.getText());
        Float temp = Float.parseFloat(temperatureJTF.getText());
        Float bloodPressure = Float.parseFloat(bloodPressurejTextField2.getText());
        Float weight = Float.parseFloat(weightjTextField3.getText());
        String Presc = presciptionjTextArea1.getText();

        //        if((RespRate == null) || (heartrate==null) || (temp==null)
        //                || (bloodPressure==null) || (weight==null))
        //        {
        //            JOptionPane.showMessageDialog(null, "Field(s) cannot be left blank.");
        //            return;
        //        }
        Encounter encounter = new Encounter();
        encounter.setDoctor(doctor);
        encounter.setEncounterDate(new Date());
        encounter.setPatient(patient);
        encounter.getPrescriptionList().add(Presc);

        encounter.getVitalSign().setBloodPressure(bloodPressure);
        encounter.getVitalSign().setHeartRate(heartrate);
        encounter.getVitalSign().setRespiratoryRate(RespRate);
        encounter.getVitalSign().setTemperature(temp);
        encounter.getVitalSign().setWeight(weight);

        JOptionPane.showMessageDialog(null, "Encounter added");

        if (enterprise instanceof HospitalEnterprise) {
            HospitalEnterprise ent = (HospitalEnterprise) enterprise;
            ent.getEncounterList().add(encounter);

        }
        if (enterprise instanceof ClinicEnterprise) {
            ClinicEnterprise ent = (ClinicEnterprise) enterprise;
            ent.getEncounterList().add(encounter);
        }
    }//GEN-LAST:event_addEncounterjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEncounterjButton1;
    private javax.swing.JTextField bloodPressurejTextField2;
    private javax.swing.JTextField heartRatejTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea presciptionjTextArea1;
    private javax.swing.JTextField respiratoryRatejTextField1;
    private javax.swing.JTextField temperatureJTF;
    private javax.swing.JTextField weightjTextField3;
    // End of variables declaration//GEN-END:variables
}
