/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Person.Doctor;
import Business.WorkQueue.DoctorToLabWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class LabTestResultsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabTestResultsJPanel
     */
    private JPanel userProcessContainer;
    private Doctor doctor;
    private Enterprise docEnt;

    public LabTestResultsJPanel(JPanel upc, Doctor doctor) {
        initComponents();
        userProcessContainer = upc;
        this.doctor = doctor;

        populateEntCombo();

    }

    private void populateEntCombo() {
        enterprisejComboBox1.removeAllItems();

        for (Enterprise e : doctor.getMyEnterpriseList()) {
            enterprisejComboBox1.addItem(e);
            populateTable(e);
        }

    }

    private void populateTable(Enterprise enterp) {
        DefaultTableModel dtm = (DefaultTableModel) labTestResultsjTable1.getModel();

        dtm.setRowCount(0);

        for (WorkRequest req : doctor.getWorkQueue().getWorkRequestList()) {
            if (req instanceof DoctorToLabWorkRequest) {
                for (Enterprise enterprise : doctor.getMyEnterpriseList()) {
                    if (enterprise.getOrganizationID() == enterp.getOrganizationID()) {
                        DoctorToLabWorkRequest dlwr = (DoctorToLabWorkRequest) req;
                        Object[] row = new Object[4];
                        row[0] = dlwr.getMRN();
                        row[1] = dlwr;
                        row[2] = dlwr.getStatus();
                        row[3] = dlwr.getResult();

                        dtm.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labTestResultsjTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        enterpriseIDjLabel2 = new javax.swing.JLabel();
        enterprisejComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();

        labTestResultsjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MRN", "Message", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(labTestResultsjTable1);

        jLabel3.setText("Enterprise ID :");

        enterpriseIDjLabel2.setText("<enterpriseID>");

        enterprisejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterprisejComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisejComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enterprise:");

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(enterprisejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterpriseIDjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterprisejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(enterpriseIDjLabel2)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterprisejComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisejComboBox1ActionPerformed
        // TODO add your handling code here:
        docEnt = (Enterprise) enterprisejComboBox1.getSelectedItem();
        if (docEnt == null) {
            return;
        }
        enterpriseIDjLabel2.setText(String.valueOf(docEnt.getOrganizationID()));

        populateTable(docEnt);

    }//GEN-LAST:event_enterprisejComboBox1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel enterpriseIDjLabel2;
    private javax.swing.JComboBox enterprisejComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labTestResultsjTable1;
    // End of variables declaration//GEN-END:variables
}
