/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Person.Doctor;
import Business.WorkQueue.DoctorToLabWorkRequest;
import Business.WorkQueue.ReferredDoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class manageReferalRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageReferalRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Doctor doctor;

    public manageReferalRequestsJPanel(JPanel upc, Doctor doctor) {
        initComponents();
        userProcessContainer = upc;
        this.doctor = doctor;
        
        populateTable();
        
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) referjTable1.getModel();

        dtm.setRowCount(0);

        for (WorkRequest req : doctor.getWorkQueue().getWorkRequestList()) {
            if (req instanceof ReferredDoctorWorkRequest) {
                ReferredDoctorWorkRequest rdwr = (ReferredDoctorWorkRequest) req;
                if (rdwr.getSender().equals(doctor)) {
                    Object[] row = new Object[5];
                    row[0] = rdwr.getPatient().getMRN();
                    row[1] = rdwr.getPatient();
                    row[2] = rdwr.getReceiver();
                    row[3] = rdwr.getRecvEnt();
                    row[4] = rdwr;

                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        referjTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        referjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MRN", "Patient", "Doctor Name", "Enterprise", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(referjTable1);

        jLabel1.setText("Referrals:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable referjTable1;
    // End of variables declaration//GEN-END:variables
}
