/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DoctorRole;

import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Pharmacy.Drug;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class ViewDrugGuidelinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDrugGuidelinesJPanel
     */
    private JPanel userProcessContainer;
    private ArrayList<PharmaceuticalCompanyEnterprise> pharmaCoList;

    public ViewDrugGuidelinesJPanel(JPanel upc, ArrayList<PharmaceuticalCompanyEnterprise> list) {
        initComponents();
        userProcessContainer = upc;
        pharmaCoList = list;

        populatePharmCoCombo();
    }

    private void populatePharmCoCombo() {
        pharmaCompanyjComboBox1.removeAllItems();

        for (PharmaceuticalCompanyEnterprise pce : pharmaCoList) {
            pharmaCompanyjComboBox1.addItem(pce);
        }
    }

    private void populateTable() {

        PharmaceuticalCompanyEnterprise pharCoEnt = (PharmaceuticalCompanyEnterprise) pharmaCompanyjComboBox1.getSelectedItem();
        if (pharCoEnt == null) {
            return;
        }
        companyIDjLabel3.setText(String.valueOf(pharCoEnt.getOrganizationID()));

        DefaultTableModel dtm = (DefaultTableModel) drugjTable1.getModel();

        dtm.setRowCount(0);
        for (Drug drug : pharCoEnt.getDrugList()) {
            {
                if (drug.getFdaStatus().equalsIgnoreCase("Approved")) {
                    Object[] row = new Object[2];
                    row[0] = drug;
                    row[1] = drug.getDrugID();

                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pharmaCompanyjComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        companyIDjLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugjTable1 = new javax.swing.JTable();
        viewMedicalGuidelinesjButton1 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        pharmaCompanyjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pharmaCompanyjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmaCompanyjComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Pharmaceutical Company:");

        jLabel2.setText("Company ID:");

        companyIDjLabel3.setText("<Company ID>");

        drugjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Drug Name", "Drug ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugjTable1);

        viewMedicalGuidelinesjButton1.setText("View Medical Guidelines >>");
        viewMedicalGuidelinesjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicalGuidelinesjButton1ActionPerformed(evt);
            }
        });

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pharmaCompanyjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(companyIDjLabel3))
                            .addComponent(jLabel1)
                            .addComponent(backjButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(viewMedicalGuidelinesjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pharmaCompanyjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(companyIDjLabel3))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(viewMedicalGuidelinesjButton1)
                .addGap(43, 43, 43)
                .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pharmaCompanyjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmaCompanyjComboBox1ActionPerformed
        // TODO add your handling code here:
        populateTable();

    }//GEN-LAST:event_pharmaCompanyjComboBox1ActionPerformed

    private void viewMedicalGuidelinesjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicalGuidelinesjButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugjTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "select a row");
            return;
        }

        Drug drug = (Drug) drugjTable1.getValueAt(selectedRow, 0);

        ViewMedicalGuidelinesJPanel vmg = new ViewMedicalGuidelinesJPanel(userProcessContainer, drug);
        userProcessContainer.add("ViewMedicalGuidelinesJP", vmg);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewMedicalGuidelinesjButton1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel companyIDjLabel3;
    private javax.swing.JTable drugjTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox pharmaCompanyjComboBox1;
    private javax.swing.JButton viewMedicalGuidelinesjButton1;
    // End of variables declaration//GEN-END:variables
}
